[package]
name = "tournament_review"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
csv = "1"
libriichi = { git = "https://github.com/ashleney/libriichi.git" }
serde_json = "1.0.145"
